---
- name: Configure Raspberry Pi as WiFi Access Point
  hosts: localhost
  become: true

  vars:
    wifi_ssid: PiFi
    wifi_password: P@ssw0rd
    student_login_id: student
    student_password: P@ssw0rd

  tasks:
    - name: Create student user id
      ansible.builtin.user:
        name: "{{ student_login_id }}"
        password: "{{ student_password | password_hash('sha512') }}"
      when: student_login_id is defined

    - name: Disable swap to save wear on microSD card
      shell:
        cmd: dphys-swapfile swapoff

    - name: Remove swap file
      shell:
        cmd: dphys-swapfile uninstall

    - name: Disable swapfile service
      ansible.builtin.service:
        name: dphys-swapfile
        enabled: false
        state: stopped

    - name: Add systemd watchdog parameter for system lock-ups
      ansible.builtin.lineinfile:
        path: /etc/systemd/system.conf
        regexp: '^RuntimeWatchdogSec'
        line: RuntimeWatchdogSec=15

    - name: Add systemd watchdog parameter for boot-up problems
      ansible.builtin.lineinfile:
        path: /etc/systemd/system.conf
        regexp: '^RebootWatchdogSec'
        line: RebootWatchdogSec=5min

    - name: Reload systemd configuration
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Enable serial console
      lineinfile:
        dest: /boot/firmware/config.txt
        insertafter: "[all]"
        line: "enable_uart=1"
      register: enable_uart

    - name: Shutdown for switchover to serial console
      ansible.builtin.shell:
        cmd: "shutdown -h now"
      when: enable_uart.changed

    - name: Check internet connection
      ansible.builtin.shell:
        cmd: nmcli networking connectivity
      register: connectivity_test

    - set_fact:
        internet_connectivity: "{{ connectivity_test.stdout }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: internet_connectivity == "full"

    - name: Install web-based Secure Shell
      ansible.builtin.apt:
        name: shellinabox
      when: internet_connectivity == "full"

    - name: Install network discovery tool
      ansible.builtin.apt:
        name: nmap
      when: internet_connectivity == "full"

    - name: Set up WiFi access point connection
      community.general.nmcli:
        conn_name: "{{ wifi_ssid | lower }}"
        type: wifi
        ifname: wlan0
        ssid: "{{ wifi_ssid }}"
        wifi:
          band: bg
          hidden: false
          mode: ap
        wifi_sec:
          key-mgmt: wpa-psk
          psk: "{{ wifi_password }}"
        method4: shared
        state: present
        autoconnect: true
      notify:
        - Activate access point mode

    - name: Set hostname to match SSID
      ansible.builtin.hostname:
        name: "{{ wifi_ssid | lower }}"
      notify:
        - Refresh Ansible facts
        - Create a new hosts file
        - Add the loopback address
        - Add this host's address(es)

  handlers:
    - name: Activate access point mode
      ansible.builtin.shell:
        cmd: "nmcli connection up {{ wifi_ssid | lower }}"

    - name: Refresh Ansible facts
      setup:

    - name: Create a new hosts file
      ansible.builtin.copy:
        content: ""
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

    - name: Add the loopback address
      ansible.builtin.lineinfile:
        path: /etc/hosts
        search_string: "127.0.0.1"
        line: "127.0.0.1\tlocalhost"

    - name: Add this host's address(es)
      ansible.builtin.lineinfile:
        path: /etc/hosts
        search_string: "{{ item }}"
        line: "{{ item }}\t{{ wifi_ssid | lower }}"
      with_items: "{{ ansible_all_ipv4_addresses }}"


# References:
# https://raspberrypi.stackexchange.com/questions/84390/how-to-permanently-disable-swap-on-raspbian-stretch-lite
# https://pimylifeup.com/raspberry-pi-watchdog/
# https://learn.adafruit.com/adafruits-raspberry-pi-lesson-5-using-a-console-cable/
# https://raymii.org/s/tutorials/Ansible_-_Only-do-something-if-another-action-changed.html
# https://raspberrytips.com/access-point-setup-raspberry-pi/
# https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/hostname_module.html
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html
