---
services:
  code-server:
    image: ghcr.io/davescodemusings/code-server-python:latest
    container_name: code-server
    hostname: code-server
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
      - DEFAULT_WORKSPACE=/Code
    volumes:
      - config:/config
      - /home/student/Code:/Code
    ports:
      - 8000:8000
    restart: unless-stopped

volumes:
  config:
