---
- name: Configure Raspberry Pi as WiFi Access Point
  hosts: localhost
  become: true

  vars:
    hostname: "{{ lookup('env', 'HOSTNAME') }}"
    wifi_ssid: "{{ hostname }}"
    wifi_password: letmein

  tasks:
    - name: Enable serial console
      lineinfile:
        dest: /boot/firmware/config.txt
        insertafter: "[all]"
        line: "enable_uart=1"
      register: enable_uart

    - name: Set up WiFi access point connection
      community.general.nmcli:
        conn_name: "{{ wifi_ssid }}"
        type: wifi
        ifname: wlan0
        ssid: "{{ wifi_ssid }}"
        wifi:
          band: bg
          hidden: false
          mode: ap
        wifi_sec:
          key-mgmt: wpa-psk
          psk: "{{ wifi_password }}"
        method4: shared
        state: present
        autoconnect: true

    - name: Disable preconfigured autoconnect
      community.general.nmcli:
        conn_name: preconfigured
        state: present
        autoconnect: false

    - name: Set hostname to match SSID
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: Create a new hosts file
      ansible.builtin.copy:
        content: |
          127.0.0.1   localhost
          10.42.0.1   {{ hostname }}
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
