---
- name: Deploy Visual Studio Code code-server as a Docker container
  hosts: localhost
  become: true

  vars:
    admin_login_id: "{{ lookup('env', 'USER') }}"
    student_login_id: student

  tasks:
    - name: Create a directory for the code-server project
      ansible.builtin.file:
        path: /var/lib/docker/compose/code-server
        state: directory
        owner: root
        group: docker
        mode: '0775'

    - name: Fetch the compose file for code-server
      ansible.builtin.get_url:
        url: https://github.com/DavesCodeMusings/school-coding-lab/raw/main/rpi/code-server/compose.yml
        dest: /var/lib/docker/compose/code-server

    - name: Start up the code-server container
      ansible.builtin.shell:
        chdir: /var/lib/docker/compose/code-server
        cmd: docker-compose up -d
      ignore_errors: yes  # Container may fail if microcontroller not plugged into USB.
