---
- name: Download lab guides locally
  hosts: localhost
  become: true

  vars:
    web_server_dir: /srv/www/lab-guides

  tasks:
    - name: Ensure web server directory exists
      ansible.builtin.file:
        path: "{{ web_server_dir }}"
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Fetch latest manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/DavesCodeMusings/school-coding-lab/main/lab-guides/MANIFEST.yml
        dest: "{{ web_server_dir }}/MANIFEST.yml"

    - name: Read available code samples from manifest
      ansible.builtin.include_vars:
        file: "{{ web_server_dir }}/MANIFEST.yml"
        name: code_samples

    - name: Download code samples locally
      ansible.builtin.get_url:
        url: " https://raw.githubusercontent.com/DavesCodeMusings/school-coding-lab/main/lab-guides/{{ item }}"
        dest: "{{ web_server_dir }}/{{ item | basename }}"
        mode: '0644'
      with_items: "{{ code_samples.labs }}"
