name: Docker Image

on:
    push:
        branches: ["main"]
    schedule:
        - cron: '0 0 15 * *'

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]')"

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup qemu for multi-arch build
              uses: docker/setup-qemu-action@v3

            - name: Setup buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: Login to Docker Container Registry
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ./rpi/code-server
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      davescodemusings/code-server-python:latest
                      ghcr.io/davescodemusings/code-server-python:latest
